### ISSUE TITLE
可否提供一个Wrapper的连线例子，帮助快速集成NOC用来连接

### ISSUE THREAD

**Issue by biquanha** [RV-BOSC/OpenNoC#1]
我想要集成测试您的OpenNoc在SOC上的效果
具体的行为是：XS*1+OpenNoc的最小系统
这至少需要一个Noc的Wrapper，包括一个CHI的入口和1-2个AXI的出口
我观察了您的代码，我注意到VCS仿真的TB对象是hnf，对于其他模块拥有单独的仿真顶层
我不了解Noc的具体构造，无法制作这个Wrapper集成
请问您是否可以提供一个Wrapper的集成示例以供研究

**Comment by faxiang1230** [comment]
1. 目前CHI <-> AXI 转换接口还在开发中，目前不可用，请等待这些组件的开发完成。
2. 附件中是一个 2x3 Mesh 的示例，里面接入了hnf，可以作为参考。
[mesh_example.tar.gz](https://github.com/user-attachments/files/16902476/mesh_example.tar.gz)
3. 计划开发一个自动mesh拓扑生成的脚本工具，以简化连线工作

**Comment by biquanha** [comment]
多谢您提供的例子，很期待OpenNoc的后续进展

**Comment by faxiang1230** [comment]
> 多谢您提供的例子，很期待OpenNoc的后续进展

@biquanha 
please close the issue if no further question.
