### ISSUE TITLE
请问case文件夹中不同txt文件的命名规则

### ISSUE THREAD

**Issue by sfyhhh** [RV-BOSC/OpenNoC#2]
您好！

能否解释txt文件的命名规则？例如下面的例子。txt中的代码是否说明一个完整的CHI协议中定义的transaction flow？我想要深入这个项目来学习使用CHI协议的NoC，但是通过readme和源码学习有些难度，请问有什么好的建议？

谢谢您们的贡献，期待该项目后续的进展！
```
I_I_I_Excl_Order00_NonCompAck_WriteNoSnpFull_I_I_I_fail.txt
```

**Comment by Zeta-96** [comment]
您好，
    感谢您的提问，很高兴您对我们的项目关心与支持！
    关于您提出 ”能否解释txt文件的命名规则？例如下面的例子。txt中的代码是否说明一个完整的CHI协议中定义的transaction flow？“ 的问题，以下是该问题的解答：
具体命名规则在 https://github.com/RV-BOSC/OpenNoC/blob/master/rtl/case/README.md 
例如：hnf_channels_NAME source_NAME hnf_channels_ID source_ID packet_ID

**Comment by gaohy1003** [comment]
现关闭此 Issue，如果针对您的问题还有没有解释清楚的，可以重新打开追加提问，感谢您的关注
