### ISSUE TITLE
如何向仓库贡献代码

### ISSUE THREAD

**Issue by tsyw** [RV-BOSC/OpenNoC#3]
您好，请问这个项目作为开源项目是完整的吗?个人如何贡献代码呢？
我个人对:
1. 标准协议组件 rtl，xp 逻辑 rtl
2. 自动化 mesh 生成工具包括 gui
3. 参考模型
这三个方面比较感兴趣。请问有什么渠道吗?

**Comment by faxiang1230** [comment]
@tsyw 

1. we are planning to make a ring bus routing  for small-scale interconnection, you can try this if interested
2. I have done a autoconfigure tool [mesh_generator.tar.gz](https://github.com/user-attachments/files/17594823/mesh_generator.tar.gz) with python for auto generate mesh, maybe help you for gui working

Thanks!

**Comment by gaohy1003** [comment]
现关闭此 Issue，如果针对您的问题还有没有解释清楚的，可以重新打开追加提问，感谢您的关注

**Comment by MengXiao92** [comment]
@faxiang1230，感谢提供的mesh_generator的工具，在给出的代码router_channel.v中缺少module **xp_find1_from_bitx**，vcs 编译直接报错，Cell ‘xp_find1_from_bitx’ cannot be found in liblist for binding instance
请问可以这个会开源吗？可以提供一下吗？非常感谢

**Comment by faxiang1230** [comment]
@MengXiao92 
sorry for late respone, 'xp_find1_from_bitx' is just alias of https://github.com/RV-BOSC/OpenNoC/blob/master/rtl/misc/xp_sel_bit_from_vec.v.
